# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-30 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0004_code_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='name'),
        ),
    ]
